map = [
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                                            '
    '                              _-g-_         '
    '                            _-.ttt.-_       '
    '                           _-.tttttt.-_     '
    '                        _-.ttttttttttt.-_   '
    'ggggggggggggggggggggggg.ggggggggggggggg.ggg'
]